pipelines:
  branches:
    develop:
      - step:
          name: Deploy on Test server
          deployment: Revving_TEST
          script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: 'ubuntu'
                  SERVER: '35.177.76.148'
                  COMMAND: >
                    cd /home/ubuntu/src_client/ && sudo git stash --include-untracked &&
                    cd /home/ubuntu/src_client/ && sudo git pull https://$GITUSER:$GITPASS@bitbucket.org/revvingadmin/client.git &&
                    cd /home/ubuntu/src_client/ && sudo yarn install && 
                    cd /home/ubuntu/src_client/ && sudo yarn build &&
                    echo 100000 | sudo tee /proc/sys/fs/inotify/max_user_watches &&
                    cd /var/www/html/wordpress/public_html/ && sudo tar -cvzf /home/ubuntu/Backups/build.$BITBUCKET_BUILD_NUMBER.tar.gz build &&
                    sudo rm -rf "/home/ubuntu/Backups/build.`expr $BITBUCKET_BUILD_NUMBER - 5`.tar.gz" &&
                    sudo cp -rf /home/ubuntu/src_client/build/* /var/www/html/wordpress/public_html/ &&
                    sudo cp -rf /home/ubuntu/src_client/build/* /var/www/html/wordpress/public_html/build/ &&
                    cd /var/www/html/wordpress/public_html/ && sudo chown -R www-data:www-data * &&
                    sudo systemctl restart nginx
                  MODE: 'command' 

      - step:
          name: Deploy on Stage server
          deployment: Revving_STAGING
          trigger: manual
          script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: 'ubuntu'
                  SERVER: '18.132.163.132'
                  COMMAND: >
                    cd /home/ubuntu/src_client/ && sudo git stash --include-untracked &&
                    cd /home/ubuntu/src_client/ && sudo git pull https://$GITUSER:$GITPASS@bitbucket.org/revvingadmin/client.git &&
                    cd /home/ubuntu/src_client/ && sudo yarn install &&
                    cd /home/ubuntu/src_client/ && sudo yarn build &&
                    echo 100000 | sudo tee /proc/sys/fs/inotify/max_user_watches &&
                    sudo systemctl restart clientyarn.service
                  MODE: 'command' 

      - step:
          name: Deploy on Prod server
          deployment: Revving_PRODUCTION
          trigger: manual
          script:
              - pipe: atlassian/ssh-run:0.3.0
                variables:
                  SSH_USER: 'ubuntu'
                  SERVER: '35.177.77.129'
                  COMMAND: >
                    cd /home/ubuntu/src_client/ && sudo git stash --include-untracked &&
                    cd /home/ubuntu/src_client/ && sudo git pull https://$GITUSER:$GITPASS@bitbucket.org/revvingadmin/client.git &&
                    cd /home/ubuntu/src_client/ && sudo yarn install &&
                    cd /home/ubuntu/src_client/ && sudo yarn format\:fix && 
                    cd /home/ubuntu/src_client/ && sudo yarn lint\:fix &&
                    cd /home/ubuntu/src_client/ && sudo yarn build &&
                    echo 100000 | sudo tee /proc/sys/fs/inotify/max_user_watches &&
                    sudo systemctl restart clientyarn.service
                  MODE: 'command'
                  